name: Stale Issue Management

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch: # Allow manual trigger

jobs:
  stale:
    name: Clean Stale Issues
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v8
      with:
        # Issue specific settings
        days-before-issue-stale: 60
        days-before-issue-close: 7
        stale-issue-message: >
          This issue has been automatically marked as stale because it has not had
          recent activity. It will be closed if no further activity occurs. Thank you
          for your contributions.
          
          If you believe this issue is still relevant and should remain open, please
          add a comment or remove the stale label.
        close-issue-message: >
          This issue has been automatically closed because it has not had recent activity.
          If you believe this issue is still relevant, please feel free to reopen it or
          create a new issue with updated information.
        stale-issue-label: 'stale'
        exempt-issue-labels: 'security,pinned,help wanted'

        # Pull request specific settings
        days-before-pr-stale: 30
        days-before-pr-close: 7
        stale-pr-message: >
          This pull request has been automatically marked as stale because it has not had
          recent activity. It will be closed if no further activity occurs. Thank you
          for your contributions.
          
          If you are still working on this PR, please add a comment or remove the stale label.
        close-pr-message: >
          This pull request has been automatically closed because it has not had recent activity.
          If you would like to continue working on this PR, please feel free to reopen it.
        stale-pr-label: 'stale'
        exempt-pr-labels: 'dependencies,security'

        # General settings
        exempt-all-milestones: true
        operations-per-run: 100
        ascending: true
        remove-stale-when-updated: true
        delete-branch: true
        enable-statistics: true

    - name: Notify Stale Issues
      if: steps.stale.outputs.staled-issues-prs > 0
      uses: actions/github-script@v6
      with:
        script: |
          const staledCount = ${{ steps.stale.outputs.staled-issues-prs }};
          const closedCount = ${{ steps.stale.outputs.closed-issues-prs }};
          
          await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: 1, // Replace with your tracking issue number
            body: `## Stale Issue Report
            
            The stale issue workflow has run with the following results:
            
            - Marked as stale: ${staledCount}
            - Closed: ${closedCount}
            
            Please review these changes to ensure no active issues were incorrectly marked.`
          });

    - name: Notify on Failure
      if: failure()
      uses: slackapi/slack-github-action@v1.23.0
      with:
        channel-id: 'github-alerts'
        slack-message: '❌ Stale issue management workflow failed'
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }} 